trigger:
  branches:
    include:
      - master

pr:
  branches:
    include:
      - master

variables:
  - name: buildConfiguration
    value: Release

stages:
- template: ./azure-pipelines-template.yml
  buildConfiguration: ${{ variables.buildConfiguration }}