variables:
  - name: buildConfiguration
    value: Release
  - group: vs-marketplace-publisher

trigger:
  include:
    - master
    - release/*
    - preview/*

stages:
- template: ./azure-pipelines-template.yml
  parameters:
    buildConfiguration: ${{ variables.buildConfiguration }}
    publish: true
    vsMarketplacePublisherToken: ${{ variables.VSMarketPlacePublisherToken }}
